ARG JAVA_VERSION

FROM itzg/minecraft-server:${JAVA_VERSION}

ARG SERVER_TYPE
ARG MINECRAFT_VERSION
ARG IMPL_VERSION

ENV VERSION ${IMPL_VERSION:-$MINECRAFT_VERSION}
ENV TYPE ${SERVER_TYPE}

ENV EULA TRUE

COPY ./copy_server_jar.sh /
RUN /copy_server_jar.sh && rm /copy_server_jar.sh

ENV CUSTOM_SERVER /server.jar
ENV TYPE CUSTOM
