ARG JAVA_VERSION

FROM itzg/minecraft-server:${JAVA_VERSION}

ARG SERVER_TYPE
ARG MINECRAFT_VERSION
ARG IMPL_VERSION

ENV VERSION ${IMPL_VERSION:-$MINECRAFT_VERSION}
ENV TYPE ${SERVER_TYPE}

ENV EULA TRUE
ENV SETUP_ONLY TRUE

RUN /start

ENV SETUP_ONLY FALSE
