name: publish docker images

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          # vanilla images
          - minecraft_version: "1.21.3"
            type: vanilla
            java: java21
          - minecraft_version: "1.21.2"
            type: vanilla
            java: java21
          - minecraft_version: "1.21.1"
            type: vanilla
            java: java21
          - minecraft_version: "1.21"
            type: vanilla
            java: java21

          - minecraft_version: "1.20.6"
            type: vanilla
            java: java21
          - minecraft_version: "1.20.5"
            type: vanilla
            java: java21
          - minecraft_version: "1.20.4"
            type: vanilla
            java: java21
          - minecraft_version: "1.20.3"
            type: vanilla
            java: java21
          - minecraft_version: "1.20.2"
            type: vanilla
            java: java21
          - minecraft_version: "1.20.1"
            type: vanilla
            java: java21
          - minecraft_version: "1.20"
            type: vanilla
            java: java21

          - minecraft_version: "1.19.4"
            type: vanilla
            java: java17
          - minecraft_version: "1.19.3"
            type: vanilla
            java: java17
          - minecraft_version: "1.19.2"
            type: vanilla
            java: java17
          - minecraft_version: "1.19.1"
            type: vanilla
            java: java17
          - minecraft_version: "1.19"
            type: vanilla
            java: java17

          - minecraft_version: "1.18.2"
            type: vanilla
            java: java17
          - minecraft_version: "1.18.1"
            type: vanilla
            java: java17
          - minecraft_version: "1.18"
            type: vanilla
            java: java17

          - minecraft_version: "1.17.1"
            type: vanilla
            java: java17
          - minecraft_version: "1.17"
            type: vanilla
            java: java17

          - minecraft_version: "1.16.5"
            type: vanilla
            java: java11
          - minecraft_version: "1.16.4"
            type: vanilla
            java: java11
          - minecraft_version: "1.16.3"
            type: vanilla
            java: java11
          - minecraft_version: "1.16.2"
            type: vanilla
            java: java11
          - minecraft_version: "1.16.1"
            type: vanilla
            java: java11

          - minecraft_version: "1.15.2"
            type: vanilla
            java: java8
          - minecraft_version: "1.15.1"
            type: vanilla
            java: java8
          - minecraft_version: "1.15"
            type: vanilla
            java: java8

          - minecraft_version: "1.14.4"
            type: vanilla
            java: java8
          - minecraft_version: "1.14.3"
            type: vanilla
            java: java8
          - minecraft_version: "1.14.2"
            type: vanilla
            java: java8
          - minecraft_version: "1.14.1"
            type: vanilla
            java: java8
          - minecraft_version: "1.14"
            type: vanilla
            java: java8

          - minecraft_version: "1.13.2"
            type: vanilla
            java: java8
          - minecraft_version: "1.13.1"
            type: vanilla
            java: java8
          - minecraft_version: "1.13"
            type: vanilla
            java: java8

          - minecraft_version: "1.12.2"
            type: vanilla
            java: java8
          - minecraft_version: "1.12.1"
            type: vanilla
            java: java8
          - minecraft_version: "1.12"
            type: vanilla
            java: java8

          - minecraft_version: "1.11.2"
            type: vanilla
            java: java8
          - minecraft_version: "1.11.1"
            type: vanilla
            java: java8
          - minecraft_version: "1.11"
            type: vanilla
            java: java8

          - minecraft_version: "1.10.2"
            type: vanilla
            java: java8
          - minecraft_version: "1.10"
            type: vanilla
            java: java8

          - minecraft_version: "1.9.4"
            type: vanilla
            java: java8
          - minecraft_version: "1.9.2"
            type: vanilla
            java: java8
          - minecraft_version: "1.9"
            type: vanilla
            java: java8

          - minecraft_version: "1.8.8"
            type: vanilla
            java: java8
          - minecraft_version: "1.8.7"
            type: vanilla
            java: java8
          - minecraft_version: "1.8.6"
            type: vanilla
            java: java8
          - minecraft_version: "1.8.5"
            type: vanilla
            java: java8
          - minecraft_version: "1.8.4"
            type: vanilla
            java: java8
          - minecraft_version: "1.8.3"
            type: vanilla
            java: java8
          - minecraft_version: "1.8"
            type: vanilla
            java: java8

          # spigot images
          - minecraft_version: "1.21.3"
            type: spigot
            java: java21
          # - minecraft_version: "1.21.2"
          #   type: spigot
          #   java: java21
          - minecraft_version: "1.21.1"
            type: spigot
            java: java21
          - minecraft_version: "1.21"
            type: spigot
            java: java21

          - minecraft_version: "1.20.6"
            type: spigot
            java: java21
          # - minecraft_version: "1.20.5"
          #   type: spigot
          #   java: java21
          # - minecraft_version: "1.20.4"
          #   type: spigot
          #   java: java21
          - minecraft_version: "1.20.3"
            type: spigot
            java: java21
          - minecraft_version: "1.20.2"
            type: spigot
            java: java21
          - minecraft_version: "1.20.1"
            type: spigot
            java: java21
          - minecraft_version: "1.20"
            type: spigot
            java: java21

          - minecraft_version: "1.19.4"
            type: spigot
            java: java17
          - minecraft_version: "1.19.3"
            type: spigot
            java: java17

          - minecraft_version: "1.19.2"
            type: spigot
            java: java17
          - minecraft_version: "1.19.1"
            type: spigot
            java: java17
          - minecraft_version: "1.19"
            type: spigot
            java: java17

          - minecraft_version: "1.18.2"
            type: spigot
            java: java17
          - minecraft_version: "1.18.1"
            type: spigot
            java: java17
          - minecraft_version: "1.18"
            type: spigot
            java: java17

          - minecraft_version: "1.17.1"
            type: spigot
            java: java17
          - minecraft_version: "1.17"
            type: spigot
            java: java16

          - minecraft_version: "1.16.5"
            type: spigot
            java: java11
          - minecraft_version: "1.16.4"
            type: spigot
            java: java11
          - minecraft_version: "1.16.3"
            type: spigot
            java: java11
          - minecraft_version: "1.16.2"
            type: spigot
            java: java11
          - minecraft_version: "1.16.1"
            type: spigot
            java: java11

          - minecraft_version: "1.15.2"
            type: spigot
            java: java8
          - minecraft_version: "1.15.1"
            type: spigot
            java: java8
          - minecraft_version: "1.15"
            type: spigot
            java: java8

          - minecraft_version: "1.14.4"
            type: spigot
            java: java8
          - minecraft_version: "1.14.3"
            type: spigot
            java: java8
          - minecraft_version: "1.14.2"
            type: spigot
            java: java8
          - minecraft_version: "1.14.1"
            type: spigot
            java: java8
          # - minecraft_version: "1.14"
          #   type: spigot
          #   java: java8

          - minecraft_version: "1.13.2"
            type: spigot
            java: java8
          - minecraft_version: "1.13.1"
            type: spigot
            java: java8
          - minecraft_version: "1.13"
            type: spigot
            java: java8

          - minecraft_version: "1.12.2"
            type: spigot
            java: java8
          - minecraft_version: "1.12.1"
            type: spigot
            java: java8
          - minecraft_version: "1.12"
            type: spigot
            java: java8

          - minecraft_version: "1.11.2"
            type: spigot
            java: java8
          - minecraft_version: "1.11.1"
            type: spigot
            java: java8
          - minecraft_version: "1.11"
            type: spigot
            java: java8

          - minecraft_version: "1.10.2"
            type: spigot
            java: java8
          - minecraft_version: "1.10"
            type: spigot
            java: java8

          - minecraft_version: "1.9.4"
            type: spigot
            java: java8
          - minecraft_version: "1.9.2"
            type: spigot
            java: java8
          - minecraft_version: "1.9"
            type: spigot
            java: java8

          - minecraft_version: "1.8.8"
            type: spigot
            java: java8
          - minecraft_version: "1.8.7"
            type: spigot
            java: java8
          - minecraft_version: "1.8.6"
            type: spigot
            java: java8
          - minecraft_version: "1.8.5"
            type: spigot
            java: java8
          - minecraft_version: "1.8.4"
            type: spigot
            java: java8
          - minecraft_version: "1.8.3"
            type: spigot
            java: java8
          - minecraft_version: "1.8"
            type: spigot
            java: java8

          # bukkit images
          - minecraft_version: "1.21.3"
            type: bukkit
            java: java21
          - minecraft_version: "1.21.2"
            type: bukkit
            java: java21
          - minecraft_version: "1.21.1"
            type: bukkit
            java: java21
          - minecraft_version: "1.21"
            type: bukkit
            java: java21

          - minecraft_version: "1.20.6"
            type: bukkit
            java: java21
          - minecraft_version: "1.20.5"
            type: bukkit
            java: java21
          - minecraft_version: "1.20.4"
            type: bukkit
            java: java21
          - minecraft_version: "1.20.3"
            type: bukkit
            java: java21
          - minecraft_version: "1.20.2"
            type: bukkit
            java: java21
          - minecraft_version: "1.20.1"
            type: bukkit
            java: java21
          - minecraft_version: "1.20"
            type: bukkit
            java: java21

          - minecraft_version: "1.19.4"
            type: bukkit
            java: java17
          - minecraft_version: "1.19.3"
            type: bukkit
            java: java17

          - minecraft_version: "1.19.2"
            type: bukkit
            java: java17
          - minecraft_version: "1.19.1"
            type: bukkit
            java: java17
          - minecraft_version: "1.19"
            type: bukkit
            java: java17

          - minecraft_version: "1.18.2"
            type: bukkit
            java: java17
          - minecraft_version: "1.18.1"
            type: bukkit
            java: java17
          - minecraft_version: "1.18"
            type: bukkit
            java: java17

          - minecraft_version: "1.17.1"
            type: bukkit
            java: java17
          - minecraft_version: "1.17"
            type: bukkit
            java: java16

          - minecraft_version: "1.16.5"
            type: bukkit
            java: java11
          # - minecraft_version: "1.16.4"
          #   type: bukkit
          #   java: java11
          - minecraft_version: "1.16.3"
            type: bukkit
            java: java11
          - minecraft_version: "1.16.2"
            type: bukkit
            java: java11
          - minecraft_version: "1.16.1"
            type: bukkit
            java: java11

          - minecraft_version: "1.15.2"
            type: bukkit
            java: java8
          - minecraft_version: "1.15.1"
            type: bukkit
            java: java8
          - minecraft_version: "1.15"
            type: bukkit
            java: java8

          - minecraft_version: "1.14.4"
            type: bukkit
            java: java8
          - minecraft_version: "1.14.3"
            type: bukkit
            java: java8
          - minecraft_version: "1.14.2"
            type: bukkit
            java: java8
          - minecraft_version: "1.14.1"
            type: bukkit
            java: java8
          - minecraft_version: "1.14"
            type: bukkit
            java: java8

          - minecraft_version: "1.13.2"
            type: bukkit
            java: java8
          - minecraft_version: "1.13.1"
            type: bukkit
            java: java8
          - minecraft_version: "1.13"
            type: bukkit
            java: java8

          - minecraft_version: "1.12.2"
            type: bukkit
            java: java8
          - minecraft_version: "1.12.1"
            type: bukkit
            java: java8
          - minecraft_version: "1.12"
            type: bukkit
            java: java8

          - minecraft_version: "1.11.2"
            type: bukkit
            java: java8
          - minecraft_version: "1.11.1"
            type: bukkit
            java: java8
          - minecraft_version: "1.11"
            type: bukkit
            java: java8

          - minecraft_version: "1.10.2"
            type: bukkit
            java: java8
          - minecraft_version: "1.10"
            type: bukkit
            java: java8

          - minecraft_version: "1.9.4"
            type: bukkit
            java: java8
          - minecraft_version: "1.9.2"
            type: bukkit
            java: java8
          - minecraft_version: "1.9"
            type: bukkit
            java: java8

          - minecraft_version: "1.8.8"
            type: bukkit
            java: java8
          - minecraft_version: "1.8.7"
            type: bukkit
            java: java8
          - minecraft_version: "1.8.6"
            type: bukkit
            java: java8
          - minecraft_version: "1.8.5"
            type: bukkit
            java: java8
          - minecraft_version: "1.8.4"
            type: bukkit
            java: java8
          - minecraft_version: "1.8.3"
            type: bukkit
            java: java8
          - minecraft_version: "1.8"
            type: bukkit
            java: java8

    steps:
      - uses: actions/checkout@v3

      - name: Echo build info
        run: echo "Building ${{ matrix.minecraft_version }} with server type ${{ matrix.type }} on ${{ matrix.java }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          registry: ${{ secrets.DOCKER_HUB_URL }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          build-args: |
            JAVA_VERSION=${{ matrix.java }}
            SERVER_TYPE=${{ matrix.type }}
            MINECRAFT_VERSION=${{ matrix.minecraft_version }}
          tags: ${{ secrets.DOCKER_HUB_PREFIX }}minecraft-servers/${{ matrix.type }}:${{ matrix.minecraft_version }}
          outputs: type=docker

      - name: Validate docker image (max 10 minutes)
        timeout-minutes: 10
        run: |
          docker images
          docker run --detach --name mcserver ${{ secrets.DOCKER_HUB_PREFIX }}minecraft-servers/${{ matrix.type }}:${{ matrix.minecraft_version }}
          until [ "$(docker inspect -f {{.State.Health.Status}} mcserver)" = "healthy" ]; do \
            sleep 60; \
            docker logs mcserver; \
          done;
          docker rm --force mcserver

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            JAVA_VERSION=${{ matrix.java }}
            SERVER_TYPE=${{ matrix.type }}
            MINECRAFT_VERSION=${{ matrix.minecraft_version }}
          tags: ${{ secrets.DOCKER_HUB_PREFIX }}minecraft-servers/${{ matrix.type }}:${{ matrix.minecraft_version }}
